import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className='container'>
      <Head>
        <title>Next Sprout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='main'>
        <h1 className='title'>
          🌱
        </h1>

        <p className='description'>
          a Next.js starter with everything you need
        </p>

        <div className='grid'>
          <a target="_blank" href="https://nextjs.org/docs/basic-features/typescript" className='card'>
            <h2>✨ Typescript</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a target="_blank" href="https://greensock.com/" className='card'>
            <h2>💫 GSAP</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            className='card'
          >
            <h2>🎨 Organized assets</h2>
            <p>
              Well organized SCSS files with views, components, and utils folder for the psycopaths like <a href="https://twitter/com/albanbleicher">Alban</a>.
            </p>
          </a>

          <a
          target="_blank"
            href="https://github.com/axios/axios"
            className='card'
          >
            <h2>📡 Axios</h2>
            <p>
              Quick and simple API fetching with Axios : Promise based HTTP client for the browser and node.js
            </p>
          </a>
        </div>
      </main>

      <footer className='footer'>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className='logo'>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
